### PR TITLE
Utilize ScanCode toolkit in LicenseCheckTask (source_licenses)

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by fridex** [comment]
With this we would probably like to reschedule license tasks to get new output for all artefacts that we have already analysed.

**Comment by miteshvp** [comment]
Yes, makes sense. I guess we may also have to run github package specific flow, correct?

**Comment by fridex** [comment]
> ... run github package specific flow, correct?

This is not related to this PR, but we eventually would like to do some one time job for github_details related transition.

**Comment by pombredanne** [comment]
@jpopelka very nice! I will be on deck if there are any bug or issues!

**Pull request merged**
