### PR TITLE
Prevent HTTP error 500 for unresolved dependencies

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**
Symptomatic remedy of issue - https://github.com/openshiftio/openshift.io/issues/659.

### CODE REVIEW

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by tisnik** [comment]
@samuzzal-choudhury thanks for the fix. Do you happen to know what's the cause of this issue? It's more important to know that IMHO.

**Comment by tisnik** [comment]
[test this]

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by jpopelka** [comment]
Ok, merging. Cause is described [here](https://github.com/openshiftio/openshift.io/issues/659#issuecomment-330278723)

**Pull request merged**
