### PR TITLE
chore: Update utils to latest.

### PR DESCRIPTION
**Pull request by rafiu007**

### CODE REVIEW

**Comment by deepak1725** [comment]
@rafiu007 Please update your pip-compile to the latest, and then regenerate requirements.txt

https://pypi.org/project/pip-tools/

**Comment by rafiu007** [comment]
> @rafiu007 Please update your pip-compile to the latest, and then regenerate requirements.txt
> 
> https://pypi.org/project/pip-tools/

Done.

**Review by deepak1725 — COMMENTED** [review]
6cb0a2d isn't latest, but `f4fef58` is.. Please check

**Review by deepak1725 — APPROVED** [review]
lgtm

**Comment by rafiu007** [comment]
> 6cb0a2d isn't latest, but `f4fef58` is.. Please check

Yes.i have moved from 6cb0a2d to `f4fef58`

**Pull request merged**
