### PR TITLE
Update nodes.yml

### PR DESCRIPTION
**Pull request by jyasveer**
updating it to the prod bucket instance to read master tags

### CODE REVIEW

**Comment by msrb** [comment]
Question: who and when populates the bucket?

**Comment by jyasveer** [comment]
bucket gets populated by analytics team when they run the offline process to validate the tags gathered from the crowd sourcing.
Server api will use this bucket only for read purpose.

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
@miteshvp @samuzzal-choudhury I will leave this one up to you guys, as you understand the problem better. But we should be careful here, make sure that random deployment on the dev cluster won't override production data.

**Comment by miteshvp** [comment]
@msrb - I agree your concerns are all valid. But we may have to trade-off between duplicating vs. shared resources. Just so that I could be of help, this bucket is not used by any analytics but rather published by them so that API can use them. SO over-all I guess we should be good, even if API manipulates it, we could get it back easily.

**Comment by jyasveer** [comment]
@miteshvp @samuzzal-choudhury can onyone of you please merge this PR ?

**Pull request merged**
