### PR TITLE
Ingest unknown stack dependencies

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**
Continuation of the unintentionally closed PR [Ingest unknown dependencies found during stack analysis](https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/60).

Comments for https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/60 holds good for this PR.

### CODE REVIEW

**Comment by samuzzal-choudhury** [comment]
@fridex decided to maintain the "unknown_deps" list as that will enable us to send the data back to the user about the not-yet-analysed dependencies and also to perform the logic to ingest only a subset of all the unknown components as Krishna suggested to me.

I am still testing this PR and also making sure that the invoke of the bayesianFlow does not ingest any transitive dependencies.

**Comment by fridex** [comment]
Related: https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/30

**Comment by fridex** [comment]
> @fridex decided to maintain the "unknown_deps" list as that will enable us to send the data back to the user about the not-yet-analysed dependencies and also to perform the logic to ingest only a subset of all the unknown components as Krishna suggested to me.

Sounds reasonable 👍 

> I am still testing this PR and also making sure that the invoke of the bayesianFlow does not ingest any transitive dependencies.

You can pass `recursive_limit` parameter to `bayesianFlow` (set it to zero). It will prevent from any transitive scans (yeah, the naming is archaic due to the old recursor task).

**Comment by msrb** [comment]
[test this]

**Comment by samuzzal-choudhury** [comment]
@msrb tested the changes before pushing. Is that what you meant?

**Comment by msrb** [comment]
@samuzzal-choudhury "[test this]" comment will trigger Jenkins build :)

**Comment by samuzzal-choudhury** [comment]
This PR no longer holds good as unknown components are going to be defined by the recommender gateway that is being developed currently. Hence closing this.

**Pull request closed without merging**
