### PR TITLE
[tests] Use pathlib to get rid of all the ugly joins

### PR DESCRIPTION
**Pull request by jpopelka**
Thanks @abs51295 for pointing me to the pathlib

### CODE REVIEW

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
@tisnik in case you have nothing to do ;-)
this is tests related, so you might take a look (and review)

**Comment by tisnik** [comment]
The usage of / operator in the Pathlib is ingenious :1st_place_medal:

**Comment by tisnik** [comment]
@jpopelka now it is far more readable. Thanks a lot!

**Pull request merged**
