### PR TITLE
remove keywords tagger and summary tasks

### PR DESCRIPTION
**Pull request by msehnout**
Details:
https://openshift.io/openshiftio/Openshift_io/plan/detail/1002

### CODE REVIEW

**Comment by msehnout** [comment]
According to my testing, it doesn't seem to break the workflow.

**Comment by msehnout** [comment]
@msrb review?

**Comment by msehnout** [comment]
For some reason, I thought you want me to keep it. It should be fine by now.

**Comment by msrb** [comment]
:+1: Thanks @msehnout :wink: Let me test locally once... I think you can drop the WIP flag. WDYT?

**Pull request merged**
