### PR TITLE
[DO NOT MERGE] mercator worker

### PR DESCRIPTION
**Pull request by vasulakkaraju**
pls do not review or merge

### CODE REVIEW

**Comment by GeetikaBatra** [comment]
[test]

**Comment by msrb** [comment]
The error looks like a web scraping issue to me. I think NPM registry website has changed and we will need to update our code.

**Comment by vasulakkaraju** [comment]
[test]

**Comment by jpopelka** [comment]
> The error looks like a web scraping issue to me. I think NPM registry website has changed and we will need to update our code.

Working on it in #587

**Comment by jpopelka** [comment]
rebase and rerun tests please

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
And CI is green folks. Thanks @jpopelka :wink:

**Comment by vasulakkaraju** [comment]
[test]

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by samuzzal-choudhury** [comment]
[test]

**Comment by samuzzal-choudhury** [comment]
This PR is not applicable any more. Hence, closing.

**Pull request closed without merging**
