### PR TITLE
Don't resolve pom files when running mercator via API

### PR DESCRIPTION
**Pull request by jpopelka**
(the last two commits are just code refactoring)

### CODE REVIEW

**Comment by tuxdna** [comment]
LGTM, good to merge.

**Comment by tuxdna** [comment]
[test this]

**Comment by jpopelka** [comment]
[E2e tests failed](https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/85/console), but it looks more like saasherder issue.

**Comment by jpopelka** [comment]
> it looks more like saasherder issue.

Fixed with https://github.com/openshiftio/saas-analytics/pull/101

**Pull request merged**
