### PR TITLE
Be more verbose on startup

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by jpopelka** [comment]
The EPEL repository has been behaving weirdly since Friday, this time it's:
```
--> Finished Dependency Resolution
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: libhttp_parser.so.2()(64bit)
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: http-parser >= 2.7.0
You could try using --skip-broken to work around the proble
```

**Comment by jpopelka** [comment]
[test this]

**Comment by jpopelka** [comment]
Can be reproduced locally: 
```sh
$ docker run -ti centos:7 bash -c "yum install -y epel-release && yum install nodejs"
--> Finished Dependency Resolution
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: libhttp_parser.so.2()(64bit)
Error: Package: 1:nodejs-6.11.1-1.el7.x86_64 (epel)
           Requires: http-parser >= 2.7.0
```

**Comment by fridex** [comment]
[test this]

**Pull request merged**
