### PR TITLE
Fix permission issues with certain types of tar packages in npm fetcher

### PR DESCRIPTION
**Pull request by pkajaba**

### CODE REVIEW

**Comment by pkajaba** [comment]
I have to provide tests in order to get this PR complete.

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
CI broken...

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
CI is finally green.

**Pull request merged**
