### PR TITLE
Small clean up

### PR DESCRIPTION
**Pull request by msrb**
Don't install `scipy` (almost 200MiB) if we don't need it.

### CODE REVIEW

**Comment by msrb** [comment]
Weird...

**Comment by msrb** [comment]
scikit-learn requires scipy, but doesn't pull it in automatically :-1: :hankey:

**Comment by jpopelka** [comment]
Then maybe you could have added a comment into the `requirements.in` about it ?

**Comment by msrb** [comment]
> Then maybe you could have added a comment into the requirements.in about it ?

Good idea: https://github.com/fabric8-analytics/fabric8-analytics-worker/pull/550

**Pull request closed without merging**
