### PR TITLE
Stop collecting data via GitHub's Search API

### PR DESCRIPTION
**Pull request by msrb**
The API rate limit is very lean - 30 requests per minute.

### CODE REVIEW

**Comment by msrb** [comment]
Related https://github.com/fabric8-analytics/fabric8-analytics-worker/issues/90.

**Comment by jpopelka** [comment]
Tests (and I guess also the schema) needs to be changed.

**Comment by msrb** [comment]
Good catch, PR updated. Let's see what Jenkins thinks now.

**Comment by msrb** [comment]
[test this]

**Comment by msrb** [comment]
[test this]

**Pull request merged**
