### PR TITLE
Separate google.protobuf hack and add test

### LINKED ISSUE #261: google.protobuf strikes back
```python
docker run -ti registry.devshift.net/bayesian/cucos-worker python3 -c 'from google.cloud import language'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/google/cloud/language/__init__.py", line 21, in <module>
    from google.cloud.language.client import Client
  File "/usr/lib/python3.4/site-packages/google/cloud/language/client.py", line 20, in <module>
    from google.cloud import client as client_module
  File "/usr/lib/python3.4/site-packages/google/cloud/client.py", line 26, in <module>
    from google.cloud._helpers import _determine_default_project
  File "/usr/lib/python3.4/site-packages/google/cloud/_helpers.py", line 30, in <module>
    from google.protobuf import duration_pb2
ImportError: No module named 'google.protobuf'
```

Tha hack (b3f836e27) was working for some time, but now it broke again.
With 270558ff we at least import it only locally, but it needs proper investigation.

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes #261

### CODE REVIEW

**Comment by fridex** [comment]
Tests failed:

> ImportError: No module named 'google.protobuf'

**Comment by jpopelka** [comment]
[test this]

**Comment by jpopelka** [comment]
what the hell ... it work's for me locally

**Comment by jpopelka** [comment]
[test this]

**Pull request merged**
