### PR TITLE
Fix pylint warnings in f8a worker

### PR DESCRIPTION
**Pull request by tisnik**
The last bunch of fixes for pylint warnings. Good luck :champagne:

### CODE REVIEW

**Comment by jpopelka** [comment]
Check the [tests](https://ci.centos.org/job/devtools-fabric8-analytics-worker-fabric8-analytics/116/console)

**Comment by pkajaba** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Pull request merged**
