### PR TITLE
[openshift] Replicas as integer

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by tuxdna** [comment]
LGTM. Merging.

**Comment by pkajaba** [comment]
any specific reason to do this? In OS guide it's done differently :-) https://docs.openshift.com/container-platform/3.5/dev_guide/templates.html (example 7)

**Comment by tuxdna** [comment]
@pkajaba Because of build failures - `Error from server: unrecognized type: int32` - https://ci.centos.org/job/devtools-f8a-master-deploy-e2e-test/322/console

**Comment by fridex** [comment]
> any specific reason to do this? In OS guide it's done differently :-) 

@pkajaba see "Changes in oc process after upgrade" on devtools saas mailing list

**Comment by pkajaba** [comment]
Thanks for response.

**Pull request merged**
