### PR TITLE
WAR/AAR support

### LINKED ISSUE #365: AAR/WAR support in IndianaJones
[maven/de.halfbit:tinybus/2.0.0](https://mvnrepository.com/artifact/de.halfbit/tinybus/2.0.0)

```
[INFO] f8a_worker.process: downloading maven package de.halfbit:tinybus:2.0.0
[DEBUG] f8a_worker.process: fetching artifact from: http://repo1.maven.org/maven2/de/halfbit/tinybus/2.0.0/tinybus-2.0.0.jar
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/de/halfbit/tinybus/2.0.0/tinybus-2.0.0.jar
```

[There's only aar file](http://repo1.maven.org/maven2/de/halfbit/tinybus/2.0.0/), which is a zip archive, containing `classes.jar` along with some resources.

The same applies to 
[maven:de.novanic.gwteventservice.demo.hellogwteventservice:hellogwteventservice:1.2.1](https://mvnrepository.com/artifact/de.novanic.gwteventservice.demo.hellogwteventservice/hellogwteventservice/1.2.1), which [has only](http://repo1.maven.org/maven2/de/novanic/gwteventservice/demo/hellogwteventservice/hellogwteventservice/1.2.1) [war file](https://en.wikipedia.org/wiki/WAR_(file_format))

```
[INFO] f8a_worker.process: downloading maven package de.novanic.gwteventservice.demo.hellogwteventservice:hellogwteventservice:1.2.1
[DEBUG] f8a_worker.process: fetching artifact from: http://repo1.maven.org/maven2/de/novanic/gwteventservice/demo/hellogwteventservice/hellogwteventservice/1.2.1/hellogwteventservice-1.2.1.jar
[ERROR] f8a_worker.process: unable to download: http://repo1.maven.org/maven2/de/novanic/gwteventservice/demo/hellogwteventservice/hellogwteventservice/1.2.1/hellogwteventservice-1.2.1.jar
```

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes #365

### CODE REVIEW

**Comment by msrb** [comment]
Hmm, I am not sure what would be the best way how to tackle this, but the default `type` (or packaging) is `jar`. If people want to use `war`, `ear`, ... you name it, they need to explicitly say so. This means that the coordinates `de.halfbit:tinybus:2.0.0` are simply not valid. Maven itself would fail to download such artifact. Correct coordinates should be `de.halfbit:tinybus:aar:2.0.0`.

**Comment by jpopelka** [comment]
> Correct coordinates should be de.halfbit:tinybus:aar:2.0.0.

I see. PTAL

**Comment by jpopelka** [comment]
Can you take another look Michal ?
There were some missing bits, so I just changed the commit to be sure that we are able to scan packages with war/aar artifacts.
One still needs to specify the proper packaging (for example `de.halfbit:tinybus:aar:2.0.0`) as you pointed out.

**Comment by msrb** [comment]
Looks good, please rebase 😉

**Pull request merged**
