### PR TITLE
[LibrariesIoTask] get recent releases

### PR DESCRIPTION
**Pull request by jpopelka**

### CODE REVIEW

**Comment by jpopelka** [comment]
CC @miteshvp

**Comment by msrb** [comment]
final json:

```json
{
  "_audit": {
    "ended_at": "2017-07-31T18:17:18.984746",
    "started_at": "2017-07-31T18:16:59.344598",
    "version": "v1"
  },
  "_release": "npm:serve-static:None",
  "details": {
    "dependent_repositories": {
      "count": "33.9K",
      "top": {
        "angular/angular": "26143",
        "angular/angular.js": "56535",
        "facebook/jest": "11332",
        "facebook/react": "71897",
        "petkaantonov/bluebird": "14858",
        "postcss/autoprefixer": "13122",
        "postcss/postcss": "15459",
        "reactjs/redux": "32613",
        "strongloop/express": "22970",
        "webpack/webpack": "30409"
      }
    },
    "dependents": {
      "count": "1.84K"
    },
    "releases": {
      "count": "49",
      "latest": {
        "published_at": "May 17, 2017",
        "recent": {
          "1.10.1": "Jan 17, 2016",
          "1.10.2": "Jan 20, 2016",
          "1.10.3": "May 31, 2016",
          "1.11.0": "Jun 8, 2016",
          "1.11.1": "Jun 11, 2016",
          "1.11.2": "Jan 23, 2017",
          "1.12.0": "Feb 26, 2017",
          "1.12.1": "Mar 5, 2017",
          "1.12.2": "Apr 27, 2017"
        },
        "version": "1.12.3"
      }
    }
  },
  "status": "success",
  "summary": []
}
```

**Comment by miteshvp** [comment]
@jpopelka - previously timestamp were captured in the format
`"published_at": "2017-05-14T16:28:30Z"`
can we please make sure, we be consistent with previous timestamp format.

**Comment by jpopelka** [comment]
@miteshvp Previously the date of the latest release was scraped from different part of the web page, where the time is in ISO format. I could keep the time of the latest release in ISO format, but the recent releases will still be in `"month day, year"` format.

I see that you [convert the time to string](https://github.com/fabric8-analytics/fabric8-analytics-data-model/blob/master/src/graph_populator.py#L146) anyway, so isn't the `"month day, year"` format actually better for you since you don't have to convert it ?

**Comment by miteshvp** [comment]
@jpopelka - in that case, let us keep it consistent. I will make necessary changes at data-importer side.

**Pull request merged**
