### PR TITLE
Crude workaround for amqp failures

### PR DESCRIPTION
**Pull request by miteshvp**

### CODE REVIEW

**Comment by fridex** [comment]
This shouldn't occur in our version as we have pinned version to 2.1.4. Based on https://github.com/celery/celery/issues/4024#issuecomment-314864073

**Comment by fridex** [comment]
OK, I think we get newer one when installing selinon.

**Comment by msrb** [comment]
@fridex we install kombu from fork and I think that is where we pull the newer version.

**Comment by msrb** [comment]
Hmm, indeed, we install selinon with pip's `-U` flag. So it's possible we will pull the newer version there.

**Pull request closed without merging**
