### PR TITLE
Ignore more exceptions in Sentry

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
@msrb hmm that pesky Codecov bot seems to be a bit unhappy with code coverage deltas ;)

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
[test]

**Comment by msrb** [comment]
@tisnik `-0.02%`

**Pull request merged**
