### PR TITLE
Update to use default behavior for pom files

### PR DESCRIPTION
**Pull request by tuxdna**

### CODE REVIEW

**Comment by tuxdna** [comment]
@fridex Can you please review this PR ?

**Comment by jpopelka** [comment]
[test]

**Comment by jpopelka** [comment]
@tuxdna I had to revert this PR, because it makes the `MercatorTask` not working as expected, see #334 

Not sure what's the proper solution, but I think the `MERCATOR_JAVA_RESOLVE_POMS` should be set conditionally, based on how the `MercatorTask` was called.

**Comment by tuxdna** [comment]
@jpopelka ACK. Will work on a solution tomorrow.

**Comment by jpopelka** [comment]
See #346

**Pull request merged**
