### PR TITLE
 [DataNormalizer/dotnet] use scancode to see what license is LicenseUrl pointing to

### LINKED ISSUE #237: declared license in nuget metadata is URL
From [.nuspec reference](https://docs.microsoft.com/en-us/nuget/schema/nuspec#optional-metadata-elements):
`licenseUrl`:  A URL for the package's license, often shown in UI displays as well as nuget.org.

We probably need to download the file that the `licenseUrl` points to and run scancode (the tool we use in license scanner) on it.

### PR DESCRIPTION
**Pull request by jpopelka**
Fixes #237

### CODE REVIEW

**Comment by jpopelka** [comment]
[test this]

**Comment by fridex** [comment]
Will wait for CI to give it green.

**Comment by jpopelka** [comment]
[test this]

**Comment by jpopelka** [comment]
green 🥇

**Pull request merged**
